/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface SpiCandidats {
    'load': () => Promise<void>;
    'name': string;
  }
  interface SpiCandidatsAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface EnseignantAffichage {
    'deletefunction': (ens: any) => Promise<void>;
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface EnseignantAffichageAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnseignantAffichagenom {
    'deletefunction': (ens: any) => Promise<void>;
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface EnseignantAffichagenomAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnseignantAjout {
    'home': RouterHistory;
  }
  interface EnseignantAjoutAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface EnseignantsHome {}
  interface EnseignantsHomeAttributes extends StencilHTMLAttributes {}

  interface EnseignantRecherche {
    'name': string;
  }
  interface EnseignantRechercheAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface EnseignantSuppression {
    'match': MatchResults;
  }
  interface EnseignantSuppressionAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface EnseignantsAffichage {
    'deletefunction': (ens: any) => Promise<void>;
    'name': string;
  }
  interface EnseignantsAffichageAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SpiCandidats': Components.SpiCandidats;
    'EnseignantAffichage': Components.EnseignantAffichage;
    'EnseignantAffichagenom': Components.EnseignantAffichagenom;
    'EnseignantAjout': Components.EnseignantAjout;
    'EnseignantsHome': Components.EnseignantsHome;
    'EnseignantRecherche': Components.EnseignantRecherche;
    'EnseignantSuppression': Components.EnseignantSuppression;
    'EnseignantsAffichage': Components.EnseignantsAffichage;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'spi-candidats': Components.SpiCandidatsAttributes;
    'enseignant-affichage': Components.EnseignantAffichageAttributes;
    'enseignant-affichagenom': Components.EnseignantAffichagenomAttributes;
    'enseignant-ajout': Components.EnseignantAjoutAttributes;
    'enseignants-home': Components.EnseignantsHomeAttributes;
    'enseignant-recherche': Components.EnseignantRechercheAttributes;
    'enseignant-suppression': Components.EnseignantSuppressionAttributes;
    'enseignants-affichage': Components.EnseignantsAffichageAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLSpiCandidatsElement extends Components.SpiCandidats, HTMLStencilElement {}
  var HTMLSpiCandidatsElement: {
    prototype: HTMLSpiCandidatsElement;
    new (): HTMLSpiCandidatsElement;
  };

  interface HTMLEnseignantAffichageElement extends Components.EnseignantAffichage, HTMLStencilElement {}
  var HTMLEnseignantAffichageElement: {
    prototype: HTMLEnseignantAffichageElement;
    new (): HTMLEnseignantAffichageElement;
  };

  interface HTMLEnseignantAffichagenomElement extends Components.EnseignantAffichagenom, HTMLStencilElement {}
  var HTMLEnseignantAffichagenomElement: {
    prototype: HTMLEnseignantAffichagenomElement;
    new (): HTMLEnseignantAffichagenomElement;
  };

  interface HTMLEnseignantAjoutElement extends Components.EnseignantAjout, HTMLStencilElement {}
  var HTMLEnseignantAjoutElement: {
    prototype: HTMLEnseignantAjoutElement;
    new (): HTMLEnseignantAjoutElement;
  };

  interface HTMLEnseignantsHomeElement extends Components.EnseignantsHome, HTMLStencilElement {}
  var HTMLEnseignantsHomeElement: {
    prototype: HTMLEnseignantsHomeElement;
    new (): HTMLEnseignantsHomeElement;
  };

  interface HTMLEnseignantRechercheElement extends Components.EnseignantRecherche, HTMLStencilElement {}
  var HTMLEnseignantRechercheElement: {
    prototype: HTMLEnseignantRechercheElement;
    new (): HTMLEnseignantRechercheElement;
  };

  interface HTMLEnseignantSuppressionElement extends Components.EnseignantSuppression, HTMLStencilElement {}
  var HTMLEnseignantSuppressionElement: {
    prototype: HTMLEnseignantSuppressionElement;
    new (): HTMLEnseignantSuppressionElement;
  };

  interface HTMLEnseignantsAffichageElement extends Components.EnseignantsAffichage, HTMLStencilElement {}
  var HTMLEnseignantsAffichageElement: {
    prototype: HTMLEnseignantsAffichageElement;
    new (): HTMLEnseignantsAffichageElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'spi-candidats': HTMLSpiCandidatsElement
    'enseignant-affichage': HTMLEnseignantAffichageElement
    'enseignant-affichagenom': HTMLEnseignantAffichagenomElement
    'enseignant-ajout': HTMLEnseignantAjoutElement
    'enseignants-home': HTMLEnseignantsHomeElement
    'enseignant-recherche': HTMLEnseignantRechercheElement
    'enseignant-suppression': HTMLEnseignantSuppressionElement
    'enseignants-affichage': HTMLEnseignantsAffichageElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'spi-candidats': HTMLSpiCandidatsElement;
    'enseignant-affichage': HTMLEnseignantAffichageElement;
    'enseignant-affichagenom': HTMLEnseignantAffichagenomElement;
    'enseignant-ajout': HTMLEnseignantAjoutElement;
    'enseignants-home': HTMLEnseignantsHomeElement;
    'enseignant-recherche': HTMLEnseignantRechercheElement;
    'enseignant-suppression': HTMLEnseignantSuppressionElement;
    'enseignants-affichage': HTMLEnseignantsAffichageElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
